server:
  port: 5004

spring:
  application:
    name: content-onboarding-service

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.framepulse.content_onboarding_service.mapper.KafkaSerializer

  config:
    import: optional:configserver:http://localhost:8888

minio:
  endpoint: http://localhost:9000 # MinIO URL
  access-key: IpdsZfiQYHdhiRCscYXM
  secret-key: 64O04OP0DTZJPkmsrZN9dobnVwtvGlfa1154wimp
  bucket: videos

